//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pronin.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class spravochnaia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public spravochnaia()
        {
            this.ucetnaya = new HashSet<ucetnaya>();
        }
    
        public int tabel_nomer { get; set; }
        public System.DateTime datarojdenia { get; set; }
        public string FIO { get; set; }
        public Nullable<int> oklad { get; set; }
        public Nullable<int> vsego { get; set; }
        public Nullable<int> doplat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ucetnaya> ucetnaya { get; set; }
    }
}
