//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pronin.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ucetnaya
    {
        public int nomer_zapisi { get; set; }
        public int tabelniy_nomer { get; set; }
        public string mouth { get; set; }
        public int oklad { get; set; }
        public int doplata { get; set; }
        public Nullable<System.DateTime> dataRogdenia { get; set; }
    
        public virtual spravochnaia spravochnaia { get; set; }
    }
}
